### ISSUE TITLE
Aborting a transaction?

### ISSUE THREAD

**Issue by DerKastellan** [meh/amnesia#46]
Hi.

When inside a block like the following, how do I abort the ongoing transaction?

```Amnesia.transaction do
< reads, writes >
end```

When I called :mnesia.abort/1, the whole process died due to an uncaught exception. Same happened when I introduced some kind of matching error in a transaction.

How does it work? How can I abort a transaction in Amnesia?

**Comment by meh** [comment]
Yeah I think I forgot to implement aborting transactions.

Can you ping me again if I don't report back in a couple days please?

**Comment by DerKastellan** [comment]
Can and will do. ;)

**Comment by DerKastellan** [comment]
@meh - this is your requested pingback. :)

**Comment by meh** [comment]
Ok, I checked some stuff around, and as things stand currently, aborting the transaction will result in an exception being raised from the transaction.

This is because usually the transaction aborting results from an error or an exception.

Do you think this behavior makes sense? Or should an explicit abort fail silently an return nil?

**Comment by DerKastellan** [comment]
I thought Mnesia was built around a concept of exceptions leading to an abort of the transaction itself, but then you get retries? I'm not really sure about how things fit together here because all I know about it I have from reading Joe Armstrong's Programming Erlang and various places.

So, in the "Programming Erlang" example the call of transaction:abort leads to a fail without an exception. As far as I see it, that function does nothing but raise an exception. So a failed transaction raises an exception, but I guess the exception is caught by mnesia:transaction and the result is simply that {:aborted, reason} is returned.

**Comment by meh** [comment]
That is the case, but since the exception system used by Elixir is a little different from the errors raised by mnesia and Erlang, in amnesia every result from the transaction is flattened out, so it returns the result if there is one, or it raises the proper exception in case of errors, including aborts, since exceptions are converted to weird aborts.

And you're right, all that `mnesia:abort` does is throwing an exception, which then returns an abort from the transaction.

What I'm saying is, if you're intending to abort a transaction, you'll have to catch an exception using amnesia, would that be a problem for you?

Because if you think it should not be an error, I could do some hacky stuff and return the aborted value as a result instead of raising an exception, kind of as a short-circuit.

**Comment by DerKastellan** [comment]
I'm not sure what you mean with "you'll have to catch an exception using amnesia?"

Do I have to catch an exception inside my Amnesia.transaction block? Do I use some :mnesia functionality?

In principle, the Amnesia.transaction macro could generate a try block around the code it executes and just return {:aborted, any} and the current behavior could go into something like Amnesia.transaction! so that the user can chose whether they prefer to have an error code or a throw.

What do you think?

**Comment by meh** [comment]
No, outside the catch would go outside the transaction call, just a normal Elixir exception.

The problem is there's already an `Amnesia.transaction!` macro, because I'm an opinionated asshole I decided the bang alternatives would be translated to the synchronized versions of mnesia functions instead of being linked to the error reporting, in retrospect that's kind of a mistake but I still prefer how that flows.

I think I'll go and make the abort raise, and have an `Amnesia.cancel` that cancels the transaction without failing.

**Comment by meh** [comment]
Alright, release new version, there are two new functions, `Amnesia.abort` and `Amnesia.cancel`, you can check the docs for them.

**Comment by DerKastellan** [comment]
Works for me. Thanks!
